name: Bug Report
description:  Report an issue to help improve the project.
labels: ["type: bug"]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Docs
      description: Make sure you went through the README file and docs
      options:
        - label: "I have went through the project's README file"
          required: true
